// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: courier/v1/courier.proto

package courierv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_CHANNEL_EMAIL       Channel = 10
	Channel_CHANNEL_TELEGRAM    Channel = 20
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0:  "CHANNEL_UNSPECIFIED",
		10: "CHANNEL_EMAIL",
		20: "CHANNEL_TELEGRAM",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_EMAIL":       10,
		"CHANNEL_TELEGRAM":    20,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_courier_v1_courier_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_courier_v1_courier_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_courier_v1_courier_proto_rawDescGZIP(), []int{0}
}

type Recipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       Channel                `protobuf:"varint,10,opt,name=channel,proto3,enum=courier.v1.Channel" json:"channel,omitempty"`
	Address       string                 `protobuf:"bytes,20,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipient) Reset() {
	*x = Recipient{}
	mi := &file_courier_v1_courier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipient) ProtoMessage() {}

func (x *Recipient) ProtoReflect() protoreflect.Message {
	mi := &file_courier_v1_courier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipient.ProtoReflect.Descriptor instead.
func (*Recipient) Descriptor() ([]byte, []int) {
	return file_courier_v1_courier_proto_rawDescGZIP(), []int{0}
}

func (x *Recipient) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *Recipient) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type SendNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,10,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Locale         string                 `protobuf:"bytes,20,opt,name=locale,proto3" json:"locale,omitempty"`
	TemplateId     string                 `protobuf:"bytes,30,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	TemplateData   map[string]string      `protobuf:"bytes,40,rep,name=template_data,json=templateData,proto3" json:"template_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Recipients     []*Recipient           `protobuf:"bytes,50,rep,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_courier_v1_courier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courier_v1_courier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_courier_v1_courier_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SendNotificationRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *SendNotificationRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendNotificationRequest) GetTemplateData() map[string]string {
	if x != nil {
		return x.TemplateData
	}
	return nil
}

func (x *SendNotificationRequest) GetRecipients() []*Recipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

type SendNotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,10,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Queued         int32                  `protobuf:"varint,20,opt,name=queued,proto3" json:"queued,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_courier_v1_courier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courier_v1_courier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_courier_v1_courier_proto_rawDescGZIP(), []int{2}
}

func (x *SendNotificationResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *SendNotificationResponse) GetQueued() int32 {
	if x != nil {
		return x.Queued
	}
	return 0
}

var File_courier_v1_courier_proto protoreflect.FileDescriptor

const file_courier_v1_courier_proto_rawDesc = "" +
	"\n" +
	"\x18courier/v1/courier.proto\x12\n" +
	"courier.v1\"Z\n" +
	"\tRecipient\x12-\n" +
	"\achannel\x18\n" +
	" \x01(\x0e2\x13.courier.v1.ChannelR\achannel\x12\x18\n" +
	"\aaddress\x18\x14 \x01(\tR\aaddressJ\x04\b\x1e\x10[\"\xd5\x02\n" +
	"\x17SendNotificationRequest\x12'\n" +
	"\x0fidempotency_key\x18\n" +
	" \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06locale\x18\x14 \x01(\tR\x06locale\x12\x1f\n" +
	"\vtemplate_id\x18\x1e \x01(\tR\n" +
	"templateId\x12Z\n" +
	"\rtemplate_data\x18( \x03(\v25.courier.v1.SendNotificationRequest.TemplateDataEntryR\ftemplateData\x125\n" +
	"\n" +
	"recipients\x182 \x03(\v2\x15.courier.v1.RecipientR\n" +
	"recipients\x1a?\n" +
	"\x11TemplateDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b<\x10[\"[\n" +
	"\x18SendNotificationResponse\x12'\n" +
	"\x0fnotification_id\x18\n" +
	" \x01(\tR\x0enotificationId\x12\x16\n" +
	"\x06queued\x18\x14 \x01(\x05R\x06queued*K\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCHANNEL_EMAIL\x10\n" +
	"\x12\x14\n" +
	"\x10CHANNEL_TELEGRAM\x10\x142o\n" +
	"\x0eCourierService\x12]\n" +
	"\x10SendNotification\x12#.courier.v1.SendNotificationRequest\x1a$.courier.v1.SendNotificationResponseB3Z1github.com/huponx/x-protogen/courier/v1;courierv1b\x06proto3"

var (
	file_courier_v1_courier_proto_rawDescOnce sync.Once
	file_courier_v1_courier_proto_rawDescData []byte
)

func file_courier_v1_courier_proto_rawDescGZIP() []byte {
	file_courier_v1_courier_proto_rawDescOnce.Do(func() {
		file_courier_v1_courier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_courier_v1_courier_proto_rawDesc), len(file_courier_v1_courier_proto_rawDesc)))
	})
	return file_courier_v1_courier_proto_rawDescData
}

var file_courier_v1_courier_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_courier_v1_courier_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_courier_v1_courier_proto_goTypes = []any{
	(Channel)(0),                     // 0: courier.v1.Channel
	(*Recipient)(nil),                // 1: courier.v1.Recipient
	(*SendNotificationRequest)(nil),  // 2: courier.v1.SendNotificationRequest
	(*SendNotificationResponse)(nil), // 3: courier.v1.SendNotificationResponse
	nil,                              // 4: courier.v1.SendNotificationRequest.TemplateDataEntry
}
var file_courier_v1_courier_proto_depIdxs = []int32{
	0, // 0: courier.v1.Recipient.channel:type_name -> courier.v1.Channel
	4, // 1: courier.v1.SendNotificationRequest.template_data:type_name -> courier.v1.SendNotificationRequest.TemplateDataEntry
	1, // 2: courier.v1.SendNotificationRequest.recipients:type_name -> courier.v1.Recipient
	2, // 3: courier.v1.CourierService.SendNotification:input_type -> courier.v1.SendNotificationRequest
	3, // 4: courier.v1.CourierService.SendNotification:output_type -> courier.v1.SendNotificationResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_courier_v1_courier_proto_init() }
func file_courier_v1_courier_proto_init() {
	if File_courier_v1_courier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_courier_v1_courier_proto_rawDesc), len(file_courier_v1_courier_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_courier_v1_courier_proto_goTypes,
		DependencyIndexes: file_courier_v1_courier_proto_depIdxs,
		EnumInfos:         file_courier_v1_courier_proto_enumTypes,
		MessageInfos:      file_courier_v1_courier_proto_msgTypes,
	}.Build()
	File_courier_v1_courier_proto = out.File
	file_courier_v1_courier_proto_goTypes = nil
	file_courier_v1_courier_proto_depIdxs = nil
}
